#!/usr/bin/env bash

############################################
# Named Colors — Gruvbox Material Dark

WHITE=0xffd4be98
RED=0xffea6962
BLACK=0xff1d2021
GREEN=0xffa9b665
BLUE=0xff7daea3
YELLOW=0xffd8a657
ORANGE=0xffe78a4e
MAGENTA=0xffd3869b
GREY=0xff928374
LIGHT_GREY=0xffa89984
DARK_GREY=0xff282828

############################################
# Accent Colors

ACCENT_PRIMARY=0xff7daea3
ACCENT_SECONDARY=0xffa9b665
ACCENT_TERTIARY=0xffe78a4e
ACCENT_QUATERNARY=0xffd3869b
ACCENT_PINK=0xffd3869b

############################################
# Default Colors

DEFAULT_LABEL_COLOR=0xff928374
DEFAULT_ICON_COLOR=0xffa89984
DEFAULT_BACKGROUND_COLOR=0x00000000
DEFAULT_BAR_COLOR=0xff1d2021

############################################
# Items Colors — muted, fewer hues

WIFI_ICON_COLOR="$BLUE"

BLUETOOTH_OFF_ICON_COLOR="$GREY"
BLUETOOTH_ON_ICON_COLOR="$BLUE"

BREW_ICON_COLOR="$BLUE"

PLAYER_LABLE_COLOR="$GREY"
PLAYER_PLAY_ICON_COLOR="$GREEN"
PLAYER_PAUSE_ICON_COLOR="$YELLOW"
PLAYER_STOP_ICON_COLOR="$ORANGE"

MIC_ICON_COLOR="$GREY"
VOLUME_ICON_COLOR="$WHITE"

RAM_ICON_COLOR="$GREEN"
DISK_ICON_COLOR="$YELLOW"
CPU_ICON_COLOR="$BLUE"
BATTERY_ICON_COLOR="$GREEN"

INPUT_LABEL_COLOR="$WHITE"

CLOCK_ICON_COLOR="$WHITE"
CLOCK_LABEL_COLOR="$GREY"

DATE_ICON_COLOR="$GREY"
DATE_LABEL_COLOR="$GREY"

SCRATCHPAD_ICON_COLOR="$GREY"
SCRATCHPAD_LABEL_COLOR="$WHITE"

FRONT_APP_LABEL_COLOR="$WHITE"
FRONT_APP_ICON_COLOR="$BLUE"

############################################
# Runners Colors — kept distinct (app brand signal), muted

RUNNER_SETTINGS_ICON_COLOR="$GREY"
RUNNER_KITTY_ICON_COLOR=0xff89b482
RUNNER_GHOSTTY_ICON_COLOR="$WHITE"
RUNNER_WEZTERM_ICON_COLOR="$BLUE"
RUNNER_BRAVE_BROWSER_ICON_COLOR="$RED"
RUNNER_IDEA_ICON_COLOR="$ORANGE"

############################################
# Workspace Colors — keep vivid for active (functional signal)

WS_DEFAULT_BG_COLOR=0x44ffffff
WS_DEFAULT_COLOR=0xff665c54
WS_ACTIVE_ICON_COLOR="$GREEN"
WS_ACTIVE_LABEL_COLOR="$GREEN"
WS_ACTIVE_BG_COLOR=0xff32302f
WS_ACTIVE_ANOTHER_DISPLAY_ICON_COLOR="$WS_DEFAULT_COLOR"
WS_ACTIVE_ANOTHER_DISPLAY_LABEL_COLOR="$WS_DEFAULT_COLOR"
WS_ACTIVE_ANOTHER_DISPLAY_BG_COLOR="$YELLOW"
WS_WIHT_CLIENTS_ICON_COLOR="$LIGHT_GREY"
WS_WIHT_CLIENTS_LABEL_COLOR="$LIGHT_GREY"
WS_WIHT_CLIENTS_BG_COLOR=0xff3c3836
WS_EMPTY_LABEL_COLOR=0xff504945

############################################
# Popup Colors

POPUP_BORDER_COLOR="$BLUE"
POPUP_BACKGROUND_COLOR=0x603c3836
